# Generated by Django 4.2.11 on 2024-03-07 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiuser',
            name='age',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
