# Generated by Django 4.2.11 on 2024-03-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_aiuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiuser',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
