# Generated by Django 4.2.11 on 2024-03-08 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_aiuser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='suppiler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suppiler_name', models.CharField(max_length=100)),
                ('invoice_number', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('upi', 'Upi'), ('card', 'Card')], default='cash', max_length=20)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'suppiler',
                'verbose_name_plural': 'suppiler',
            },
        ),
    ]
