# Generated by Django 4.2.11 on 2024-03-08 11:55

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_suppiler'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppiler',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None, unique=True),
        ),
    ]
