# Generated by Django 4.2.11 on 2024-03-08 11:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_suppiler_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(null=True)),
                ('batch_id', models.CharField(max_length=50)),
                ('exp_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('suppiler_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.suppiler')),
            ],
            options={
                'verbose_name': 'medicine',
                'verbose_name_plural': 'medicine',
            },
        ),
    ]
