# Generated by Django 4.2.11 on 2024-03-08 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
