# Generated by Django 4.2.11 on 2024-03-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_invoiceitem_grand_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='grand_total',
        ),
        migrations.AddField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
            preserve_default=False,
        ),
    ]
