# Generated by Django 4.2.11 on 2024-03-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_remove_invoiceitem_grand_total_invoice_grand_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='grand_total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
