# Generated by Django 4.2.11 on 2024-03-15 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_rename_dr_address_customer_dr_hospital'),
    ]

    operations = [
        migrations.RenameField(
            model_name='suppiler',
            old_name='invoice_number',
            new_name='company_name',
        ),
    ]
