# Generated by Django 4.2.11 on 2024-03-16 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_rename_invoice_number_suppiler_company_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='exp_date',
            field=models.DateTimeField(null=True),
        ),
    ]
