# Generated by Django 4.2.11 on 2024-03-16 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_alter_medicine_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
